### ISSUE TITLE
请问项目有使用greendao吗

### ISSUE THREAD

**Issue by byzyhm** [Gui-kai/YiGou#1]
好像没使用是吗？

**Comment by guikaiAndroid** [comment]
是的，因为存在兼容问题，所以去掉了

**Comment by byzyhm** [comment]
> 是的，因为存在兼容问题，所以去掉了

那，用的什么取代呢？用户信息持久化没集成吗？

**Comment by byzyhm** [comment]
> 是的，因为存在兼容问题，所以去掉了

具体兼容问题不好解决吗，我现在在看这段视频，敲代码，，，有什么坑吗？

**Comment by byzyhm** [comment]
> 是的，因为存在兼容问题，所以去掉了

集成了，暂时没遇到问题

**Comment by guikaiAndroid** [comment]
老师在最后课程的重构中提到，电商项目主要数据是请求网络获取，没必要使用数据库，greendao估计已经修复了兼容性的问题，所以现在应该可以正常使用
