### ISSUE TITLE
购物车删除按钮的逻辑错的比较严重

### ISSUE THREAD

**Issue by byzyhm** [Gui-kai/YiGou#2]
还有，点击item左边勾勾的时候，应该更新全选按钮（不能一直保持全选状态），，，嗯，，，

**Comment by guikaiAndroid** [comment]
兄弟 你自己可以改改塞 又不难 还有 你是清华的？

**Comment by guikaiAndroid** [comment]
或者你拉个分支 提交修复代码 我帮你Merged到我的代码里

**Comment by byzyhm** [comment]
> 或者你拉个分支 提交修复代码 我帮你Merged到我的代码里

写过不少购物车，才说的，，来学习的，，具体业务开发时候再管了。。我直接跳过了。。。不是清华的（这真是个好名字，，哈哈哈）

**Comment by byzyhm** [comment]
写过不少购物车，才说的，，来学习的，，具体业务开发时候再管了。。我直接跳过了。。。不是清华的（这真是个好名字，，哈哈哈）
